import { invoke, isTauri } from "@tauri-apps/api/core";
import { useCallback, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import type { GrowthStory, JourneyMilestone } from "../types/cognitiveTypes";
import "./ThoughtGrowthStoryCard.css";

type Props = {
  thoughtId: string;
  open: boolean;
  onClose: () => void;
};

function maturityEmoji(maturity: string): string {
  switch (maturity) {
    case "seedling":
      return "🌱";
    case "growing":
      return "🌿";
    case "mature":
      return "🌳";
    default:
      return "🌱";
  }
}

function milestoneIcon(eventType: string): string {
  switch (eventType) {
    case "created":
      return "💡";
    case "substantial-change":
      return "✏️";
    case "challenge-review-pass":
      return "✅";
    case "challenge-review-attempt":
      return "🔄";
    case "promoted":
      return "⬆️";
    default:
      return "📌";
  }
}

function generateMarkdown(story: GrowthStory): string {
  const lines: string[] = [
    `## ${maturityEmoji(story.currentMaturity)} ${story.thoughtTitle} — 成长故事`,
    "",
  ];

  if (story.contentPreview) {
    lines.push(`> ${story.contentPreview}`, "");
  }

  lines.push(
    `从 ${story.journey[0]?.date ?? story.createdAt.slice(5, 10)} 开始追踪，历时 ${story.totalDays} 天：`,
    "",
  );

  for (const m of story.journey) {
    lines.push(`- ${m.date} ${m.description}`);
  }

  lines.push(
    "",
    `共经历 ${story.totalChallenges} 次挑战 · 通过率 ${Math.round(story.passRate * 100)}% · 历时 ${story.totalDays} 天`,
    "",
    "---",
    "*Generated by KnowForge*",
  );

  return lines.join("\n");
}

function JourneyTimeline({ journey }: { journey: JourneyMilestone[] }) {
  return (
    <div className="growth-story__timeline">
      {journey.map((m, i) => (
        <div key={`${m.date}-${i}`} className="growth-story__timeline-item">
          <span className="growth-story__timeline-icon">{milestoneIcon(m.eventType)}</span>
          <span className="growth-story__timeline-date">{m.date}</span>
          <span className="growth-story__timeline-desc">{m.description}</span>
        </div>
      ))}
    </div>
  );
}

export function ThoughtGrowthStoryCard({ thoughtId, open, onClose }: Props) {
  const { t } = useTranslation();
  const [story, setStory] = useState<GrowthStory | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!open || !thoughtId) return;
    let cancelled = false;
    setLoading(true);
    setError(null);
    setStory(null);

    if (!isTauri()) {
      setLoading(false);
      return;
    }

    invoke<GrowthStory>("get_thought_growth_story", { thoughtId })
      .then((res) => {
        if (!cancelled) setStory(res);
      })
      .catch((e) => {
        if (!cancelled) setError(e instanceof Error ? e.message : String(e));
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [open, thoughtId]);

  const handleExportMarkdown = useCallback(() => {
    if (!story) return;
    const md = generateMarkdown(story);
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `growth-story-${story.thoughtId}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }, [story]);

  const handleExportImage = useCallback(async () => {
    if (!story || !isTauri()) return;
    try {
      const { invoke: tauriInvoke } = await import("@tauri-apps/api/core");
      const md = generateMarkdown(story);
      await tauriInvoke("export_growth_story_as_image", {
        thoughtId: story.thoughtId,
        markdown: md,
      });
    } catch (e) {
      console.error("Export image failed:", e);
    }
  }, [story]);

  if (!open) return null;

  return (
    <div className="growth-story-overlay" onClick={onClose}>
      <div className="growth-story-card" onClick={(e) => e.stopPropagation()}>
        <div className="growth-story-card__header">
          <span className="growth-story-card__title">
            {t("growthStory.title", "成长故事")}
          </span>
          <button className="growth-story-card__close" onClick={onClose} aria-label="Close">
            ✕
          </button>
        </div>

        {loading && <div className="growth-story-card__loading">{t("growthStory.loading", "加载中…")}</div>}

        {error && <div className="growth-story-card__error">{error}</div>}

        {story && (
          <div className="growth-story-card__body">
            <div className="growth-story-card__summary">
              <span className="growth-story-card__maturity">
                {maturityEmoji(story.currentMaturity)} {story.thoughtTitle}
              </span>
              <span className="growth-story-card__stats">
                {story.totalDays}{t("growthStory.days", " 天")} · {story.totalChallenges}{t("growthStory.challenges", " 次挑战")}
              </span>
            </div>

            <JourneyTimeline journey={story.journey} />

            <div className="growth-story-card__footer">
              <button className="growth-story-card__btn" onClick={handleExportMarkdown}>
                {t("growthStory.exportMarkdown", "导出 Markdown")}
              </button>
              <button className="growth-story-card__btn growth-story-card__btn--secondary" onClick={handleExportImage}>
                {t("growthStory.exportImage", "导出图片")}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
